api = "0.2"

[buildpack]
id = "heroku/maven"
version = "0.1"
name = "Java"

  [publish.Ignore]
  files = [
    "etc/",
    "spec/",
    "test/",
    "vendor/",
    ".gitignore",
    ".github/",
    ".travis.yml",
    "circle.yml",
    "hatchet.json",
    "Gemfile",
    "Gemfile.lock"
  ]

[[stacks]]
id = "heroku-18"